# displays a box
print(" please enter a character to use for the robot eyes ")
character = input()
print("Beep's expression is now as follows:")
print("##############")
print("#            #")
print(f"#   {character}   {character}    #")
print("#     l      #")
print("#     l      #")
print("#   ######   #")
print("##############")
print("     ####     ")
print("    ##   ##    ")
print("   ##     ##   ")
print("##         ##")
print("#           #")
